apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawapay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pawapay
  template:
    metadata:
      labels:
        app: pawapay
    spec:
      containers:
        - name: pawapay
          image: dulcinee/pawapay
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pawapay-service
spec:
  selector:
    app: pawapay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
